[package]
name = "livekit-runtime"
version = "0.3.0"
license = "Apache-2.0"
description = "Async runtime compatibility layer for LiveKit"
edition = "2021"
repository = "https://github.com/livekit/rust-sdks"

[features]
# By default ws TLS is not enabled
default = ["runtime-tokio"]
runtime-tokio = ["tokio"]

[dependencies]
tokio = { version = "1", default-features = false, optional = true, features = [
    "rt",
    "rt-multi-thread",
] }
